FROM node:18.16

WORKDIR /usr/front

EXPOSE 19000

COPY package.json .
COPY package-lock.json .
COPY .env .
COPY updateEnv.js .

RUN npm install 
RUN node updateEnv.js

# COPY . .

CMD [ "npm", "start" ]
