# Generated by Django 4.2.2 on 2023-07-09 21:10

import authentification.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opl_key', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('cover_i', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('pages_read', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='BookData',
        ),
        migrations.AlterModelManagers(
            name='userdata',
            managers=[
                ('objects', authentification.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
