FROM python:3.10

WORKDIR /usr/back

COPY Pipfile .
COPY Pipfile.lock .

RUN pip install pipenv==2022.10.25
RUN pipenv install --deploy --ignore-pipfile 
RUN pipenv install djangorestframework

EXPOSE 8000:8000
COPY . .

CMD ["pipenv","run" ,"python3", "manage.py", "runserver", "0.0.0.0:8000"]
